/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Protected_rootRouteImport } from './routes/protected/__root'
import { Route as Auth_rootRouteImport } from './routes/auth/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/protected/dashboard'
import { Route as AuthVerifyMfaRouteImport } from './routes/auth/verify-mfa'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const Protected_rootRoute = Protected_rootRouteImport.update({
  id: '/protected/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_rootRoute = Auth_rootRouteImport.update({
  id: '/auth/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/protected/dashboard',
  path: '/protected/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMfaRoute = AuthVerifyMfaRouteImport.update({
  id: '/auth/verify-mfa',
  path: '/auth/verify-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof Auth_rootRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/protected': typeof Protected_rootRoute
  '/protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof Auth_rootRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/protected': typeof Protected_rootRoute
  '/protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/__root': typeof Auth_rootRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-mfa': typeof AuthVerifyMfaRoute
  '/protected/__root': typeof Protected_rootRoute
  '/protected/dashboard': typeof ProtectedDashboardRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-mfa'
    | '/protected'
    | '/protected/dashboard'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-mfa'
    | '/protected'
    | '/protected/dashboard'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/auth/__root'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-mfa'
    | '/protected/__root'
    | '/protected/dashboard'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Auth_rootRoute: typeof Auth_rootRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyMfaRoute: typeof AuthVerifyMfaRoute
  Protected_rootRoute: typeof Protected_rootRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protected/__root': {
      id: '/protected/__root'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof Protected_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__root': {
      id: '/auth/__root'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/dashboard': {
      id: '/protected/dashboard'
      path: '/protected/dashboard'
      fullPath: '/protected/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mfa': {
      id: '/auth/verify-mfa'
      path: '/auth/verify-mfa'
      fullPath: '/auth/verify-mfa'
      preLoaderRoute: typeof AuthVerifyMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Auth_rootRoute: Auth_rootRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyMfaRoute: AuthVerifyMfaRoute,
  Protected_rootRoute: Protected_rootRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
