// Code generated by tygo. DO NOT EDIT.

//////////
// source: asset_dto.go
/*
Package dto defines data transfer objects for API request/response handling.

This package contains structured types for API contracts, providing
validation, serialization, and documentation support for all endpoints.
All DTOs include JSON tags and validation annotations.
*/

/**
 * AssetResponse represents an asset in API responses.
 */
export interface AssetResponse {
  id: string;
  name: string;
  description: string;
  version: string;
  project_id: string;
  repository_id?: string;
  created_at: string;
  updated_at: string;
  /**
   * Optional nested relationships
   */
  project?: ProjectSummaryResponse;
  repository?: RepositoryResponse;
  pipeline_ids?: string[];
}
/**
 * AssetSummaryResponse represents a simplified asset for nested responses.
 */
export interface AssetSummaryResponse {
  id: string;
  name: string;
  version: string;
  description: string;
}
/**
 * CreateAssetRequest represents the request to create a new asset.
 */
export interface CreateAssetRequest {
  name: string;
  description: string;
  version: string;
  project_id: string;
  repository_id?: string;
}
/**
 * UpdateAssetRequest represents the request to update an asset.
 */
export interface UpdateAssetRequest {
  name?: string;
  description?: string;
  version?: string;
  repository_id?: string;
}
/**
 * AssetListResponse represents a paginated list of assets.
 */
export interface AssetListResponse {
  assets: AssetResponse[];
  total: number /* int64 */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * AssetSearchResponse represents search results for assets.
 */
export interface AssetSearchResponse {
  assets: AssetResponse[];
  total: number /* int64 */;
  query: string;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * AssetVersionHistoryResponse represents the version history of an asset.
 */
export interface AssetVersionHistoryResponse {
  asset_name: string;
  versions: AssetVersion[];
}
/**
 * AssetVersion represents a single version of an asset.
 */
export interface AssetVersion {
  id: string;
  version: string;
  created_at: string;
  updated_at: string;
}
/**
 * AssetDeleteResponse represents the response when an asset is deleted.
 */
export interface AssetDeleteResponse {
  message: string;
}
/**
 * RepositoryResponse represents a repository in API responses.
 */
export interface RepositoryResponse {
  id: string;
  url: string;
  branch: string;
  latest_commit: string;
  sync_status: string;
  project_id: string;
  created_at: string;
  updated_at: string;
}
/**
 * RepositorySummaryResponse represents a simplified repository for nested
 * responses.
 */
export interface RepositorySummaryResponse {
  id: string;
  url: string;
  branch: string;
}
/**
 * ProjectSummaryResponse represents a simplified project for nested responses.
 */
export interface ProjectSummaryResponse {
  id: string;
  name: string;
  description: string;
  visibility: string;
}
/**
 * AssetPipelineResponse represents a pipeline in API responses for asset
 * context.
 */
export interface AssetPipelineResponse {
  id: string;
  name: string;
  description: string;
  project_id: string;
  created_at: string;
  updated_at: string;
  assets?: AssetSummaryResponse[];
}
/**
 * AssetValidationErrorResponse represents validation errors for asset
 * operations.
 */
export interface AssetValidationErrorResponse {
  error: string;
  code: string;
  details?: { [key: string]: string[]};
  fields?: AssetValidationError[];
}
/**
 * AssetValidationError represents a single field validation error.
 */
export interface AssetValidationError {
  field: string;
  message: string;
  value?: string;
}
/**
 * AssetMetricsResponse represents metrics for assets.
 */
export interface AssetMetricsResponse {
  total_assets: number /* int64 */;
  assets_by_project: ProjectAssetCount[];
  assets_by_version: { [key: string]: number /* int64 */};
  recent_activity: AssetActivityItem[];
}
/**
 * ProjectAssetCount represents asset count per project.
 */
export interface ProjectAssetCount {
  project_id: string;
  project_name: string;
  count: number /* int64 */;
}
/**
 * AssetActivityItem represents recent asset activity.
 */
export interface AssetActivityItem {
  asset_id: string;
  asset_name: string;
  action: string;
  timestamp: string;
  user_id: string;
  user_name: string;
}

//////////
// source: auth_dto.go
/*
Package dto defines data transfer objects for API requests and responses.

This package contains the DTOs used for authentication-related HTTP requests
and responses in the YAWN API. All DTOs include proper JSON tags and
validation
tags for request binding and response formatting.

Design principles:
  - Separate request and response DTOs for clarity
  - Use appropriate JSON tags for field names
  - Include validation tags where applicable
  - Provide clear documentation for each field
  - Follow Go naming conventions
*/

/**
 * RegisterRequest represents a user registration request.
 */
export interface RegisterRequest {
  email: string;
  password: string;
}
/**
 * RegisterResponse represents a user registration response.
 */
export interface RegisterResponse {
  id: string;
  email: string;
  role: string;
}
/**
 * LoginRequest represents a user login request.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * UserInfo represents basic user information returned in login response.
 */
export interface UserInfo {
  id: string;
  email: string;
  role: string;
}
/**
 * LoginResponse represents a user login response with JWT tokens.
 */
export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: number /* int */;
  user: UserInfo;
}
/**
 * RefreshRequest represents a token refresh request.
 */
export interface RefreshRequest {
  refresh_token: string;
}
/**
 * RefreshResponse represents a token refresh response.
 */
export interface RefreshResponse {
  access_token: string;
  token_type: string;
  expires_in: number /* int */;
}
/**
 * LogoutRequest represents a logout request.
 */
export interface LogoutRequest {
  access_token: string;
}
/**
 * LogoutResponse represents a logout response.
 */
export interface LogoutResponse {
  message: string;
}
/**
 * ErrorResponse represents a standard error response.
 */
export interface ErrorResponse {
  error: string;
  code: string;
  details?: string;
}

//////////
// source: gitops_dto.go
/*
Package dto defines data transfer objects for API request/response handling.

This package contains structured types for API contracts, providing
validation, serialization, and documentation support for all endpoints.
All DTOs include JSON tags and validation annotations.
*/

/**
 * SyncRepositoryResponse represents the response for repository
 * synchronization.
 */
export interface SyncRepositoryResponse {
  success: boolean;
  commit_hash: string;
  message: string;
  pipelines: string[];
  duration: string;
  synced_at: string;
  changes: SyncChangesResponse;
  errors?: string[];
}
/**
 * SyncChangesResponse represents synchronization changes.
 */
export interface SyncChangesResponse {
  added: string[];
  modified: string[];
  deleted: string[];
}
/**
 * WebhookRequest represents a Git webhook request.
 */
export interface WebhookRequest {
  event_type: string;
  repo_url: string;
  branch: string;
  commit: string;
  timestamp: string;
  payload: { [key: string]: any};
}
/**
 * WebhookResponse represents the response for webhook processing.
 */
export interface WebhookResponse {
  success: boolean;
  message: string;
  timestamp: string;
}
/**
 * ValidateRepositoryRequest represents the request to validate a repository.
 */
export interface ValidateRepositoryRequest {
  url: string;
  branch: string;
}
/**
 * ValidateRepositoryResponse represents the response for repository validation.
 */
export interface ValidateRepositoryResponse {
  valid: boolean;
  message: string;
  url: string;
  latest_commit?: CommitInfoResponse;
}
/**
 * CommitInfoResponse represents Git commit information.
 */
export interface CommitInfoResponse {
  hash: string;
  message: string;
  author: string;
  email: string;
  timestamp: string;
  branch: string;
}
/**
 * PendingSyncRequest represents the request to get pending synchronizations.
 */
export interface PendingSyncRequest {
  limit: number /* int */;
}
/**
 * PendingSyncResponse represents repositories that need synchronization.
 */
export interface PendingSyncResponse {
  repositories: PendingRepositoryResponse[];
  total: number /* int */;
  limit: number /* int */;
  message?: string;
}
/**
 * PendingRepositoryResponse represents a repository that needs synchronization.
 */
export interface PendingRepositoryResponse {
  id: string;
  url: string;
  branch: string;
  sync_status: string;
  last_sync?: string;
  last_attempt?: string;
  project?: ProjectSummaryResponse;
}
/**
 * SyncStatusRequest represents the request to get sync status.
 */
export interface SyncStatusRequest {
  repository_id: string;
}
/**
 * SyncStatusResponse represents the synchronization status of a repository.
 */
export interface SyncStatusResponse {
  repository_id: string;
  status: string;
  message: string;
  last_sync?: string;
  next_sync?: string;
  sync_count: number /* int */;
  error_count: number /* int */;
  latest_commit?: string;
  pipeline_count: number /* int */;
}
/**
 * GitRepositoryResponse represents a Git repository in API responses.
 */
export interface GitRepositoryResponse {
  id: string;
  url: string;
  branch: string;
  latest_commit: string;
  sync_status: string;
  project_id: string;
  created_at: string;
  updated_at: string;
  project?: ProjectSummaryResponse;
  assets?: AssetSummaryResponse[];
  sync_info?: RepositorySyncInfo;
}
/**
 * RepositorySyncInfo represents detailed synchronization information.
 */
export interface RepositorySyncInfo {
  last_sync?: string;
  next_sync?: string;
  sync_count: number /* int */;
  error_count: number /* int */;
  last_error?: string;
  duration?: string;
  pipeline_count: number /* int */;
}
/**
 * GitRepositoryListResponse represents a paginated list of Git repositories.
 */
export interface GitRepositoryListResponse {
  repositories: GitRepositoryResponse[];
  total: number /* int64 */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * GitRepositorySearchResponse represents search results for repositories.
 */
export interface GitRepositorySearchResponse {
  repositories: GitRepositoryResponse[];
  total: number /* int64 */;
  query: string;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * PipelineDefinitionResponse represents a pipeline definition from Git.
 */
export interface PipelineDefinitionResponse {
  name: string;
  description: string;
  path: string;
  content: string;
  hash: string;
  metadata: { [key: string]: any};
  updated_at: string;
}
/**
 * PipelineDiscoveryResponse represents the result of pipeline discovery.
 */
export interface PipelineDiscoveryResponse {
  success: boolean;
  message: string;
  pipelines: PipelineDefinitionResponse[];
  count: number /* int */;
  commit: string;
  branch: string;
}
/**
 * GitOpsMetricsResponse represents GitOps metrics and statistics.
 */
export interface GitOpsMetricsResponse {
  total_repositories: number /* int64 */;
  active_repositories: number /* int64 */;
  pending_sync: number /* int64 */;
  failed_sync: number /* int64 */;
  sync_rate: number /* float64 */;
  average_sync_duration: string;
  last_sync_time?: string;
  repositories_by_status: RepositoryStatusCount[];
  recent_syncs: RecentSyncActivity[];
  pipeline_stats: GitOpsPipelineStats;
}
/**
 * RepositoryStatusCount represents repository count by status.
 */
export interface RepositoryStatusCount {
  status: string;
  count: number /* int64 */;
}
/**
 * RecentSyncActivity represents recent synchronization activity.
 */
export interface RecentSyncActivity {
  repository_id: string;
  repository_url: string;
  status: string;
  duration: string;
  timestamp: string;
}
/**
 * GitOpsPipelineStats represents pipeline statistics from Git operations.
 */
export interface GitOpsPipelineStats {
  total_pipelines: number /* int64 */;
  from_git: number /* int64 */;
  manually_created: number /* int64 */;
  last_import_count: number /* int64 */;
  last_import_time?: string;
}
/**
 * GitOpsConfigResponse represents GitOps configuration.
 */
export interface GitOpsConfigResponse {
  sync_interval: string;
  sync_timeout: string;
  max_concurrent_syncs: number /* int */;
  webhook_secret?: string;
  default_branch: string;
  pipeline_patterns: string[];
  settings: { [key: string]: any};
}
/**
 * GitOpsConfigRequest represents the request to update GitOps configuration.
 */
export interface GitOpsConfigRequest {
  sync_interval?: string;
  sync_timeout?: string;
  max_concurrent_syncs?: number /* int */;
  webhook_secret?: string;
  default_branch?: string;
  pipeline_patterns?: string[];
  settings?: { [key: string]: any};
}
/**
 * GitValidationErrorResponse represents validation errors for Git operations.
 */
export interface GitValidationErrorResponse {
  error: string;
  code: string;
  details?: { [key: string]: string[]};
  fields?: GitValidationError[];
}
/**
 * GitValidationError represents a single Git validation error.
 */
export interface GitValidationError {
  field: string;
  message: string;
  value?: string;
}

//////////
// source: pipeline_dto.go
/*
Package dto defines data transfer objects for API request/response handling.

This package contains structured types for API contracts, providing
validation, serialization, and documentation support for all endpoints.
All DTOs include JSON tags and validation annotations.
*/

/**
 * PipelineResponse represents a pipeline in API responses.
 */
export interface PipelineResponse {
  id: string;
  name: string;
  description: string;
  project_id: string;
  status: string;
  config?: string;
  schedule?: string;
  is_enabled: boolean;
  created_at: string;
  updated_at: string;
  /**
   * Optional nested relationships
   */
  project?: ProjectSummaryResponse;
  assets?: AssetSummaryResponse[];
  executions?: PipelineExecutionResponse[];
  dependencies?: PipelineDependencyResponse[];
  dependents?: PipelineDependencyResponse[];
}
/**
 * PipelineSummaryResponse represents a simplified pipeline for nested
 * responses.
 */
export interface PipelineSummaryResponse {
  id: string;
  name: string;
  status: string;
  is_enabled: boolean;
}
/**
 * CreatePipelineRequest represents the request to create a new pipeline.
 */
export interface CreatePipelineRequest {
  name: string;
  description: string;
  config: string;
  schedule: string;
  project_id: string;
  asset_ids?: string[];
}
/**
 * UpdatePipelineRequest represents the request to update a pipeline.
 */
export interface UpdatePipelineRequest {
  name?: string;
  description?: string;
  config?: string;
  schedule?: string;
  status?: string;
  is_enabled?: boolean;
  asset_ids?: string[];
}
/**
 * PipelineListResponse represents a paginated list of pipelines.
 */
export interface PipelineListResponse {
  pipelines: PipelineResponse[];
  total: number /* int64 */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * PipelineSearchResponse represents search results for pipelines.
 */
export interface PipelineSearchResponse {
  pipelines: PipelineResponse[];
  total: number /* int64 */;
  query: string;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * PipelineDeleteResponse represents the response when a pipeline is deleted.
 */
export interface PipelineDeleteResponse {
  message: string;
}
/**
 * PipelineExecutionResponse represents a pipeline execution in API responses.
 */
export interface PipelineExecutionResponse {
  id: string;
  pipeline_id: string;
  status: string;
  trigger_type: string;
  triggered_by?: string;
  started_at?: string;
  completed_at?: string;
  duration: number /* int */;
  config?: string;
  logs?: string;
  error_msg?: string;
  created_at: string;
  updated_at: string;
  /**
   * Optional nested relationships
   */
  pipeline?: PipelineSummaryResponse;
  trigger_user?: UserSummaryResponse;
  steps?: ExecutionStepResponse[];
}
/**
 * ExecutionStepResponse represents an execution step in API responses.
 */
export interface ExecutionStepResponse {
  id: string;
  execution_id: string;
  name: string;
  type: string;
  status: string;
  config?: string;
  result?: string;
  error_msg?: string;
  started_at?: string;
  completed_at?: string;
  duration: number /* int */;
  order: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * PipelineExecutionListResponse represents a paginated list of pipeline
 * executions.
 */
export interface PipelineExecutionListResponse {
  executions: PipelineExecutionResponse[];
  total: number /* int64 */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * TriggerExecutionRequest represents the request to trigger a pipeline
 * execution.
 */
export interface TriggerExecutionRequest {
  config?: string;
}
/**
 * TriggerExecutionResponse represents the response when triggering an
 * execution.
 */
export interface TriggerExecutionResponse {
  execution?: PipelineExecutionResponse;
  message: string;
}
/**
 * CancelExecutionResponse represents the response when cancelling an execution.
 */
export interface CancelExecutionResponse {
  message: string;
}
/**
 * PipelineDependencyResponse represents a pipeline dependency in API responses.
 */
export interface PipelineDependencyResponse {
  id: string;
  pipeline_id: string;
  depends_on_pipeline_id: string;
  condition?: string;
  created_at: string;
  /**
   * Optional nested relationships
   */
  pipeline?: PipelineSummaryResponse;
  depends_on?: PipelineSummaryResponse;
}
/**
 * CreateDependencyRequest represents the request to create a pipeline
 * dependency.
 */
export interface CreateDependencyRequest {
  depends_on_pipeline_id: string;
  condition?: string;
}
/**
 * DependencyGraphResponse represents a dependency graph for pipelines.
 */
export interface DependencyGraphResponse {
  nodes: DependencyNodeResponse[];
  edges: DependencyEdgeResponse[];
}
/**
 * DependencyNodeResponse represents a node in the dependency graph.
 */
export interface DependencyNodeResponse {
  id: string;
  name: string;
  status: string;
}
/**
 * DependencyEdgeResponse represents an edge in the dependency graph.
 */
export interface DependencyEdgeResponse {
  from: string;
  to: string;
  condition?: string;
}
/**
 * UserSummaryResponse represents a simplified user for nested responses.
 */
export interface UserSummaryResponse {
  id: string;
  email: string;
  role: string;
}
/**
 * PipelineMetricsResponse represents metrics for pipelines.
 */
export interface PipelineMetricsResponse {
  total_pipelines: number /* int64 */;
  pipelines_by_status: { [key: string]: number /* int64 */};
  pipelines_by_project: ProjectPipelineCount[];
  recent_executions: PipelineExecutionSummary[];
  execution_stats: PipelineExecutionStats;
}
/**
 * ProjectPipelineCount represents pipeline count per project.
 */
export interface ProjectPipelineCount {
  project_id: string;
  project_name: string;
  count: number /* int64 */;
}
/**
 * PipelineExecutionSummary represents a summary of a pipeline execution.
 */
export interface PipelineExecutionSummary {
  execution_id: string;
  pipeline_id: string;
  pipeline_name: string;
  status: string;
  trigger_type: string;
  duration: number /* int */;
  started_at: string;
  completed_at?: string;
}
/**
 * PipelineExecutionStats represents execution statistics.
 */
export interface PipelineExecutionStats {
  total_executions: number /* int64 */;
  successful_runs: number /* int64 */;
  failed_runs: number /* int64 */;
  average_duration: number /* float64 */;
  executions_by_status: { [key: string]: number /* int64 */};
  executions_by_type: { [key: string]: number /* int64 */};
}
/**
 * PipelineValidationErrorResponse represents validation errors for pipeline
 * operations.
 */
export interface PipelineValidationErrorResponse {
  error: string;
  code: string;
  details?: { [key: string]: string[]};
  fields?: PipelineValidationError[];
}
/**
 * PipelineValidationError represents a single field validation error.
 */
export interface PipelineValidationError {
  field: string;
  message: string;
  value?: string;
}
/**
 * PipelineConfig represents the configuration structure for a pipeline.
 */
export interface PipelineConfig {
  version: string;
  description: string;
  steps: PipelineStepConfig[];
  variables?: { [key: string]: any};
  timeout?: number /* int */; // Timeout in seconds
  retries?: number /* int */;
}
/**
 * PipelineStepConfig represents a step configuration within a pipeline.
 */
export interface PipelineStepConfig {
  name: string;
  type: string;
  description?: string;
  config?: { [key: string]: any};
  depends_on?: string[];
  condition?: string;
  timeout?: number /* int */; // Timeout in seconds
  continue_on_error?: boolean;
}

//////////
// source: project_dto.go
/*
Package dto defines data transfer objects for API requests and responses.

This package contains the DTOs used for project management HTTP requests
and responses in the YAWN API. All DTOs include proper JSON tags and
validation tags for request binding and response formatting.

Design principles:
  - Separate request and response DTOs for clarity
  - Use appropriate JSON tags for field names
  - Include validation tags where applicable
  - Provide clear documentation for each field
  - Follow Go naming conventions
*/

/**
 * CreateProjectRequest represents a project creation request.
 */
export interface CreateProjectRequest {
  name: string;
  description?: string;
  repository?: string;
  visibility?: string;
}
/**
 * UpdateProjectRequest represents a project update request.
 */
export interface UpdateProjectRequest {
  name?: string;
  description?: string;
  repository?: string;
  visibility?: string;
}
/**
 * ProjectResponse represents project information returned by API endpoints.
 */
export interface ProjectResponse {
  id: string;
  name: string;
  description?: string;
  repository?: string;
  visibility: string;
  owner: UserInfo;
  created_at: string;
  updated_at: string;
  members?: ProjectMemberInfo[];
}
/**
 * ProjectMemberInfo represents information about a project member.
 */
export interface ProjectMemberInfo {
  user_id: string;
  email: string;
  role: string;
  created_at: string;
}
/**
 * ProjectListResponse represents a paginated list of projects.
 */
export interface ProjectListResponse {
  projects: ProjectResponse[];
  total: number /* int */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * AddProjectMemberRequest represents a request to add a member to a project.
 */
export interface AddProjectMemberRequest {
  email: string;
  role: string;
}
/**
 * UpdateProjectMemberRequest represents a request to update a project member
 * role.
 */
export interface UpdateProjectMemberRequest {
  role: string;
}
/**
 * ProjectMemberResponse represents a project member response.
 */
export interface ProjectMemberResponse {
  user_id: string;
  email: string;
  role: string;
  created_at: string;
  updated_at: string;
}
/**
 * ProjectMemberListResponse represents a list of project members.
 */
export interface ProjectMemberListResponse {
  members: ProjectMemberResponse[];
  total: number /* int */;
}
/**
 * ProjectDeleteResponse represents a successful project deletion response.
 */
export interface ProjectDeleteResponse {
  message: string;
}

//////////
// source: user_dto.go
/*
Package dto defines data transfer objects for API requests and responses.

This package contains the DTOs used for user management HTTP requests
and responses in the YAWN API. All DTOs include proper JSON tags and
validation
tags for request binding and response formatting.
*/

/**
 * UserResponse represents user information returned by API endpoints.
 */
export interface UserResponse {
  id: string;
  email: string;
  role: string;
  created_at: string;
  updated_at: string;
}
/**
 * UserListResponse represents a paginated list of users.
 */
export interface UserListResponse {
  users: UserResponse[];
  total: number /* int */;
  page: number /* int */;
  limit: number /* int */;
}
/**
 * UpdateUserRequest represents a user update request.
 */
export interface UpdateUserRequest {
  email?: string;
  role?: string;
}
/**
 * UserDeleteResponse represents a successful user deletion response.
 */
export interface UserDeleteResponse {
  message: string;
}
