// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go
/*
Package models defines domain models for the YAWN application.

Contains core entities: User, Project, Asset, Repository, Pipeline, and
relationship models.
Uses UUID v7 primary keys, GORM soft deletes, and supports PostgreSQL/SQLite.
*/

/**
 * User represents a system user with authentication and authorization.
 */
export interface User {
  id: string;
  email: string;
  role: UserRole;
  created_at: string;
  updated_at: string;
}
/**
 * UserRole represents the role of a user in the system.
 */
export type UserRole = string;
export const UserRoleAdmin: UserRole = "admin";
export const UserRoleUser: UserRole = "user";
/**
 * Project represents a project that groups assets, repositories, and users.
 */
export interface Project {
  id: string;
  name: string;
  description: string;
  repository?: string;
  visibility: string;
  owner_id: string;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  owner?: User;
  users?: ProjectUser[];
  assets?: Asset[];
  repositories?: Repository[];
}
/**
 * Asset represents a deployable asset within a project.
 */
export interface Asset {
  id: string;
  name: string;
  description: string;
  version: string;
  project_id: string;
  repository_id?: string;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  project?: Project;
  repository?: Repository;
  pipelines?: Pipeline[];
}
/**
 * Repository represents a Git repository connected to a project.
 */
export interface Repository {
  id: string;
  url: string;
  branch: string;
  latest_commit: string;
  sync_status: RepositoryStatus;
  project_id: string;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  project?: Project;
  assets?: Asset[];
}
/**
 * RepositoryStatus represents the synchronization status of a repository.
 */
export type RepositoryStatus = string;
export const RepositoryStatusPending: RepositoryStatus = "pending";
export const RepositoryStatusSuccess: RepositoryStatus = "success";
export const RepositoryStatusError: RepositoryStatus = "error";
/**
 * Pipeline represents a deployment pipeline for processing assets.
 */
export interface Pipeline {
  id: string;
  name: string;
  description: string;
  project_id: string;
  status: PipelineStatus;
  config?: string;
  schedule?: string;
  is_enabled: boolean;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  project?: Project;
  assets?: Asset[];
  executions?: PipelineExecution[];
  dependencies?: PipelineDependency[];
  dependents?: PipelineDependency[];
}
/**
 * PipelineStatus represents the current status of a pipeline.
 */
export type PipelineStatus = string;
export const PipelineStatusDraft: PipelineStatus = "draft";
export const PipelineStatusActive: PipelineStatus = "active";
export const PipelineStatusPaused: PipelineStatus = "paused";
export const PipelineStatusRunning: PipelineStatus = "running";
export const PipelineStatusCompleted: PipelineStatus = "completed";
export const PipelineStatusFailed: PipelineStatus = "failed";
export const PipelineStatusCancelled: PipelineStatus = "cancelled";
/**
 * PipelineExecution represents a specific execution of a pipeline.
 */
export interface PipelineExecution {
  id: string;
  pipeline_id: string;
  status: ExecutionStatus;
  trigger_type: string;
  triggered_by?: string;
  started_at?: string;
  completed_at?: string;
  duration: number /* int */; // Duration in seconds
  config?: string;
  logs?: string;
  error_msg?: string;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  pipeline?: Pipeline;
  trigger_user?: User;
  steps?: ExecutionStep[];
}
/**
 * ExecutionStatus represents the status of a pipeline execution.
 */
export type ExecutionStatus = string;
export const ExecutionStatusPending: ExecutionStatus = "pending";
export const ExecutionStatusRunning: ExecutionStatus = "running";
export const ExecutionStatusCompleted: ExecutionStatus = "completed";
export const ExecutionStatusFailed: ExecutionStatus = "failed";
export const ExecutionStatusCancelled: ExecutionStatus = "cancelled";
export const ExecutionStatusTimeout: ExecutionStatus = "timeout";
/**
 * ExecutionStep represents a step within a pipeline execution.
 */
export interface ExecutionStep {
  id: string;
  execution_id: string;
  name: string;
  type: StepType;
  status: ExecutionStatus;
  config?: string;
  result?: string;
  error_msg?: string;
  started_at?: string;
  completed_at?: string;
  duration: number /* int */; // Duration in seconds
  order: number /* int */;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  execution?: PipelineExecution;
}
/**
 * StepType represents the type of execution step.
 */
export type StepType = string;
export const StepTypeTask: StepType = "task";
export const StepTypeCondition: StepType = "condition";
export const StepTypeNotification: StepType = "notification";
export const StepTypeApproval: StepType = "approval";
/**
 * PipelineDependency represents a dependency relationship between pipelines.
 */
export interface PipelineDependency {
  id: string;
  pipeline_id: string;
  depends_on_pipeline_id: string;
  condition?: string; // Dependency condition
  created_at: string;
  /**
   * Relationships with proper constraints
   */
  pipeline?: Pipeline;
  depends_on?: Pipeline;
}
/**
 * ProjectUser represents the many-to-many relationship between projects and
 * users.
 */
export interface ProjectUser {
  id: string;
  project_id: string;
  user_id: string;
  role: ProjectRole;
  created_at: string;
  updated_at: string;
  /**
   * Relationships with proper constraints
   */
  project?: Project;
  user?: User;
}
/**
 * ProjectRole represents the role of a user within a project.
 */
export type ProjectRole = string;
export const ProjectRoleOwner: ProjectRole = "owner";
export const ProjectRoleMaintainer: ProjectRole = "maintainer";
export const ProjectRoleViewer: ProjectRole = "viewer";
/**
 * AssetPipeline represents the many-to-many relationship between assets and
 * pipelines.
 */
export interface AssetPipeline {
  id: string;
  pipeline_id: string;
  asset_id: string;
  order: number /* int */;
  created_at: string;
  /**
   * Relationships with proper constraints
   */
  pipeline?: Pipeline;
  asset?: Asset;
}
