/*
Copyright © 2025 Aditya Wardianto <hi@ditwrd.dev>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

// Package repositories defines the data access layer for the YAWN application.
//
// This package contains repository interfaces and their implementations that handle
// data persistence and retrieval operations. Repositories abstract the underlying
// data storage mechanism and provide a clean interface for the business logic layer.
//
// Design pattern:
// The repositories follow the Repository pattern from Domain-Driven Design (DDD):
// - Define interfaces that represent collections of domain objects
// - Hide implementation details of data storage
// - Provide domain-oriented access to data
// - Support testability through interface-based design
//
// Current repositories:
//   - UserRepository: Handles user data persistence and retrieval
//
// Data persistence:
// The current implementation uses GORM as the ORM with support for:
// - PostgreSQL and SQLite databases
// - Automatic migrations
// - Soft deletes
// - Transactions
// - Query building
//
// Example usage:
//
//	// Create a repository with a database connection
//	userRepo := repositories.NewUserRepository(db)
//
//	// Use the repository to persist a user
//	err := userRepo.Create(user)
//
//	// Retrieve a user by email
//	user, err := userRepo.GetByEmail("user@example.com")
//
// Testing:
// Repository interfaces can be easily mocked for unit testing of business logic,
// allowing tests to run without actual database dependencies.
package repositories

import (
	"github.com/ditwrd/yawn/api/internal/domain/models"
	"gorm.io/gorm"
)

// UserRepository defines the data access interface for user operations.
//
// This interface provides a contract for user data persistence and retrieval
// operations, abstracting the underlying database implementation. It follows
// the Repository pattern from Domain-Driven Design and enables easy testing
// through interface-based design.
//
// Operations:
//   - Create: Persist a new user to the database
//   - GetByID: Retrieve a user by UUID
//   - GetByEmail: Retrieve a user by email address
//   - Update: Update an existing user in the database
//   - Delete: Soft delete a user from the database
//   - List: Retrieve a paginated list of users
//
// Database behavior:
//   - Uses GORM ORM for database operations
//   - Supports soft deletes through GORM's DeletedAt field
//   - Handles UUID primary keys
//   - Supports both PostgreSQL and SQLite
//
// Error handling:
// Implementations should return GORM errors directly, which can be
// checked for specific error types like gorm.ErrRecordNotFound.
//
// Example usage:
//
//	repo := repositories.NewUserDatabase(db)
//
//	// Create a user
//	user := &models.User{Email: "user@example.com", ...}
//	err := repo.Create(user)
//
//	// Find user by email
//	user, err := repo.GetByEmail("user@example.com")
//	if errors.Is(err, gorm.ErrRecordNotFound) {
//		// Handle not found case
//	}
type UserRepository interface {
	// Create persists a new user to the database
	//
	// This method inserts a new user record into the database.
	// The user ID should be generated by the database (UUID v7).
	//
	// Parameters:
	//   - user: The user to create (ID will be ignored and generated)
	//
	// Returns:
	//   - error: GORM error if the operation fails (duplicate, constraint violation, etc.)
	//
	// Database effects:
	//   - Inserts a new record in the users table
	//   - Automatically sets CreatedAt and UpdatedAt timestamps
	//   - Generates UUID v7 primary key
	Create(user *models.User) error

	// GetByID retrieves a user by their unique identifier
	//
	// Parameters:
	//   - id: The UUID string of the user to retrieve
	//
	// Returns:
	//   - *models.User: The user if found
	//   - error: gorm.ErrRecordNotFound if user doesn't exist, other GORM errors for failures
	//
	// Note:
	// This method respects soft deletes and will not return deleted users.
	GetByID(id string) (*models.User, error)

	// GetByEmail retrieves a user by their email address
	//
	// This method is commonly used for authentication operations.
	// Email addresses should be unique in the database.
	//
	// Parameters:
	//   - email: The email address of the user to retrieve
	//
	// Returns:
	//   - *models.User: The user if found
	//   - error: gorm.ErrRecordNotFound if user doesn't exist, other GORM errors for failures
	//
	// Note:
	// This method respects soft deletes and will not return deleted users.
	GetByEmail(email string) (*models.User, error)

	// Update updates an existing user in the database
	//
	// This method updates all fields of the user record.
	// The user ID must be valid and exist in the database.
	//
	// Parameters:
	//   - user: The user data to update (must include valid ID)
	//
	// Returns:
	//   - error: gorm.ErrRecordNotFound if user doesn't exist, other GORM errors for failures
	//
	// Database effects:
	//   - Updates the user record with the provided data
	//   - Automatically updates the UpdatedAt timestamp
	Update(user *models.User) error

	// Delete soft deletes a user by their unique identifier
	//
	// This method performs a soft delete by setting the DeletedAt timestamp
	// rather than permanently removing the record from the database.
	//
	// Parameters:
	//   - id: The UUID string of the user to delete
	//
	// Returns:
	//   - error: GORM error if the operation fails
	//
	// Database effects:
	//   - Sets the DeletedAt timestamp on the user record
	//   - Record remains in the database but is excluded from normal queries
	Delete(id string) error

	// List retrieves a paginated list of users
	//
	// Parameters:
	//   - limit: Maximum number of users to return
	//   - offset: Number of users to skip (for pagination)
	//
	// Returns:
	//   - []models.User: Slice of users (may be empty if no users exist)
	//   - error: GORM error if the operation fails
	//
	// Pagination:
	// - limit: Controls the maximum number of results (use 0 for no limit)
	// - offset: Skips the specified number of results (use 0 for first page)
	//
	// Example:
	//   - First page: List(20, 0)
	//   - Second page: List(20, 20)
	//   - Third page: List(20, 40)
	//
	// Note:
	// This method respects soft deletes and will not return deleted users.
	// Results are typically ordered by CreatedAt in descending order (newest first).
	List(limit, offset int) ([]models.User, error)
}

// userRepository is a GORM-based implementation of the UserRepository interface.
//
// This struct provides the concrete implementation of user data persistence
// operations using GORM as the ORM (Object-Relational Mapping) layer.
// It encapsulates database operations and provides a clean interface
// for the business logic layer.
//
// Fields:
//   - db: GORM database instance for performing database operations
//
// Database support:
// This implementation supports any database that GORM supports, including:
// - PostgreSQL (recommended for production)
// - SQLite (recommended for development/testing)
// - MySQL, MariaDB, SQL Server, etc.
//
// Features:
// - Automatic migrations (if configured)
// - Soft deletes through GORM's DeletedAt field
// - Transaction support
// - Connection pooling
// - Query logging (if configured)
type userRepository struct {
	// db is the GORM database instance used for all user operations
	db *gorm.DB
}

// NewUserRepository creates a new GORM-based UserRepository implementation.
//
// This factory function creates a new instance of the userRepository with
// the provided GORM database connection. The database connection should
// be properly configured and connected before calling this function.
//
// Parameters:
//   - db: A valid GORM database instance with established connection
//
// Returns:
//   - UserRepository: An implementation of the UserRepository interface
//
// Example usage:
//
//	// Initialize database connection
//	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
//	if err != nil {
//		log.Fatal(err)
//	}
//
//	// Create repository
//	userRepo := repositories.NewUserRepository(db)
//
//	// Use repository
//	user, err := userRepo.GetByEmail("user@example.com")
//
// Dependency injection:
// This function is designed to work with dependency injection containers
// like Uber FX for proper lifecycle management.
//
//	func NewUserRepository(db *gorm.DB) repositories.UserRepository {
//		return repositories.NewUserRepository(db)
//	}
//
// Database requirements:
// The provided GORM instance should:
// - Be connected to a supported database
// - Have the users table created (auto-migration can be used)
// - Be configured with appropriate connection pooling
// - Have proper error handling configured
func NewUserRepository(db *gorm.DB) UserRepository {
	return &userRepository{db: db}
}

func (r *userRepository) Create(user *models.User) error {
	return r.db.Create(user).Error
}

func (r *userRepository) GetByID(id string) (*models.User, error) {
	var user models.User
	err := r.db.Where("id = ?", id).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *userRepository) GetByEmail(email string) (*models.User, error) {
	var user models.User
	err := r.db.Where("email = ?", email).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *userRepository) Update(user *models.User) error {
	return r.db.Save(user).Error
}

func (r *userRepository) Delete(id string) error {
	return r.db.Where("id = ?", id).Delete(&models.User{}).Error
}

func (r *userRepository) List(limit, offset int) ([]models.User, error) {
	var users []models.User
	err := r.db.Limit(limit).Offset(offset).Find(&users).Error
	return users, err
}